config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  get 'comments/index'

  get 'users/index'

  get 'users/show'

  get 'users/new'
  get 'users/index'

  get 'articles/show'
  get 'articles/new'
  post 'articles/create'

  root 'articles#index'

  resources :users
  
  resources :articles do
    resources :comments
  end

  resources :comments do
    resources :comments
  end

end

app/models/article.rb
class Article < ActiveRecord::Base
 belongs_to :user
 has_many :comments, as: :commentable
 validates_presence_of :title, :text
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :article
  belongs_to :commentable, polymorphic: true
  belongs_to :comments, as: :commentable
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
	has_many :articles, dependent: :destroy
	has_many :comments, as: :commentable
	validates :name, presence: true, length: { maximum: 50 }
	validates :password, presence: true, length: { minimum: 6 }


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

 before_filter :configure_permitted_parameters, if: :devise_controller?

    protected

        def configure_permitted_parameters
            devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :email,
             :password,:password_confirmation) }
            devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:name, :email, 
            :password, :current_password) }
        end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
before_action :set_user, only: [:show, :edit, :update]

  def index
    @articles = Article.all
  end

  def show
  end


  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    if @article.save
      flash[:success] = "article created!"
      redirect_to articles
    else
      render 'new'
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    flash[:success] = "article deleted"
    redirect_to article_path(@article)
    
  end

  

  private

  def set_user
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :text)
  end
  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	def index
		@commentable = comment_params
		@comments = @commentable.comments
	end

	def show
	end

  def new
  	@comment = Comment.new
  end

  def edit
  end

  def create
    @parent = Article.find(params[:article_id]) if params[:article_id]
  	@parent = Comment.find(params[:comment_id]) if params[:comment_id]
  	@comment = @parent.comments.build(comment_params)
  	@comment.user = current_user
  	if @comment.save
  		flash[:notice] = "successfully created comment"
  		redirect_to :back
  	else 
  		render 'new'
  	end
  end

  def update
  end

  def destroy
    @comment = Comment.find(params[:id])
    if @comment.present?
      @comment.destroy
      flash[:success] = "comment deleted succcefully"
    end
    redirect_to root_url
  end

 private

  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def show
  end

  def edit
  end

  def update
        respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

    private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/users_helper.rb
module UsersHelper


	# def log_in(user)
	# 	session[:user_id] = user.id 
	# end

	# # Remembers a user in a persistent session.
 #  def remember(user)
 #    user.remember
 #    cookies.permanent.signed[:user_id] = user.id
 #    cookies.permanent[:remember_token] = user.remember_token
 #  end

 #  # Returns the user corresponding to the remember token cookie.
 #  def current_user
 #    if (user_id = session[:user_id])
 #      @current_user ||= User.find_by(id: user_id)
 #    elsif (user_id = cookies.signed[:user_id])
 #      user = User.find_by(id: user_id)
 #      if user && user.authenticated?(:remember, cookies[:remember_token])
 #        log_in user
 #        @current_user = user
 #      end
 #    end
 #  end
  
	# def logged_in?
	# 	!current_user.nil?
	# end
end

app/views/articles/_articles.html.erb
<%= form_for(@article) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :text, placeholder: "Compose new article..." %>
  </div>
  <%= f.submit "Post", class: "btn btn-primary" %>
<% end %>

app/views/articles/index.html.erb
<h1>Listing Articles</h1>
<%= link_to 'New article', new_article_path %>
<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
    <th colspan="3"></th>
  </tr>
 
  <% @articles.each do |article| %>
    <tr>
      <td><%= article.title %></td>
      <td><%= article.text %></td>
      <td><%= link_to 'Show', article_path(article) %></td>
      <td><%= link_to 'Edit', edit_article_path(article) %></td>
      <td><%= link_to 'Destroy', article_path(article),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

app/views/articles/new.html.erb
<h2>New Article</h2>
<%= form_for :article, url: articles_path do |f| %>

<p><%= f.label :title %>
	<%= f.text_field :title %>
</p>

<p><%= f.label :text %>
<%= f.text_area :text %>
</p>

<p>
	<%= f.submit "Create a article", class: "btn btn-lg btn-primary" %>
</p>
<% end %>

app/views/articles/show.html.erb
<h1>Article</h1>
 <span class="timestamp">
   Posted <%= time_ago_in_words(@article.created_at) %> ago.
   <%= link_to "delete", @article, method: :delete,
                                     data: { confirm: "You sure?" } %>
<h1><%= @article.title %></h1>
<p><%= @article.text %></p>

app/views/comments/_comment.html.erb
<%= commentable.body %>
	<%= render partial:  'comments/form', locals: { commentable: commentable } %>
  <span class="timestamp">
    Posted <%= time_ago_in_words(commentable.created_at) %> ago.
    <% if current_user?(commentable.user) %>
    <%= link_to "delete", commentable, method: :delete,
                                     data: { confirm: "You sure?" } %>
    <% end %>
  </span>

app/views/comments/_form.html.erb
<%= form_for [commentable, Comment.new] do |f| %>
	<div class="form-group">
		<%= f.label :comment %>
		<%= f.text_area :body, class:"form-control", placeholder: "Add a comment" %>
	</div>
	<%= f.submit class:"btn btn-primary" %>
<% end %>

app/views/comments/index.html.erb
<div id="comments">
	<% for comment in @comments %>
	<div class="comments">
		<%=simple_format comment.content %>
	</div>
	<% end %>
</div>

<h2>New Comment</h2>

<% form_for [@commentable, Comment.new] do |f| %>
  <p>
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </p>
  <p><%= f.submit "Submit" %></p>
<% end %>

app/views/layouts/_header.html.erb
  <header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "magazine", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <% if user_signed_in? %>
        <li><%= link_to "Users", users_path %></li>
        <li>
          <%= link_to "Log out", destroy_user_session_path, method: "delete" %>
        </li>
        <% else %>
        <li><%= link_to "Log in", new_user_session_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Magazine</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/header' %>
<div class="container">
 <p class="notice"><%= notice %></p>
 <p class="alert"><%= alert %></p>
<%= yield %>
<div>

</body>
</html>

app/views/users/_form.html.erb
<h1>Update your profile</h1>
<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<%= form_for :user do |f| %>

		<%= f.label :name %>
		<%= f.text_field :name, class: 'form-control' %>

		<%= f.label :email %>
		<%= f.email_field :email, class: 'form-control' %>

		<%= f.label :password %>
		<%= f.password_field :password, class: 'form-control' %>

		<%= f.label :password_confirmation, "cconfirmation" %>
		<%= f.password_field, class: 'form-control' %>

		<%= f.submit "Save changes", class: "btn btn-lg btn-default" %>
		<% end %>
	</div>
</div>

app/views/users/_user.html.erb
<li>
  <%= link_to user.name, user %>
  | <%= link_to "delete", user, method: :delete,
                     data: { confirm: "You sure?" } %>
</li>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user, class: "btn btn-primary"  %> |
<%= link_to 'Back', users_path, class: "btn btn-primary"  %>

app/views/users/index.html.erb
<h1>All Users</h1>

<ul class="users">
	<% @users.each do |user| %>
		<%= render user %> 
	<% end %>
</ul>

app/views/users/new.html.erb
<h1>Sign up<h1>
	<div class="row">
		<div class="col-md-6 col-md-offset-3">
			<%= form_for(@user) do |f| %>

			<%= f.label :name %>
			<%= f.text_field :name, class: 'form-control' %>

			<%= f.label :email %>
			<%= f.email_field :email, class: 'form-control' %>

			<%= f.label :password %>
			<%= f.password_field :password, class: 'form-control' %>

			<%= f.label :password_confirmation, "confirmation" %>
			<%= f.password_field :password_confirmation, class: 'form-control' %>

			<%= f.submit "Sign up", class: "btn btn-default" %>

			<% end %>
		</div>
	</div>

app/views/users/show.html.erb
<div class="jumbotron">
	<h1>Welcome to Magazine<h1>
		<%= link_to "Sign up", users_new_path, class: "btn btn-lg btn-default" %>
</div>
<div class="row">
  <aside class="col-md-4">
    <section>
      <h1>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
  <div class="col-md-8">

    <% if @user.articles.any? %>
      <h3>articles (<%= @user.articles.count %>)</h3>
      <ol class="articles">
        <%= render @articles %>
      </ol>
    <% end %>
  </div>
</div>